on:
  repository_dispatch:

jobs:
  build:
    name: "[${{ github.event.client_payload.id }}] Windows engines build ${{ github.event.client_payload.commit }}"
    env:
      SQLITE_MAX_VARIABLE_NUMBER: 250000
      SQLITE_MAX_EXPR_DEPTH: 10000
    runs-on: windows-latest
    steps:
      - name: $ {{ github.event.client_payload.commit }}
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.client_payload.commit }}

      - name: Cache Rust dependencies
        uses: actions/cache@v1.1.2
        with:
          path: target
          key: ${{ runner.OS }}-build-${{ hashFiles('**\Cargo.lock') }}
          restore-keys: |
            ${{ runner.OS }}-build-
            
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

      - uses: actions/upload-artifact@v2
        with:
          name: binaries
          path: ${{ github.workspace }}/target/release/*.exe
